// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypfacorxcofjijtczsrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwZmFjb3J4Y29mamlqdGN6c3JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMTQ2MTIsImV4cCI6MjA2Nzc5MDYxMn0.WZeACaZJ8pU8fgR1RdZcUXm5FQqK1QWwqEVs9eW-VLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});